.TH "jni/EntreeTarget.h" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/EntreeTarget.h \- 
.PP
Provides class definition of entree targets.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEntreeTarget\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char * \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides class definition of entree targets. 


.SH "Typedef Documentation"
.PP 
.SS "typedef char* \fBstring\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
