.TH "jni/EntreeTarget.cpp" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/EntreeTarget.cpp \- 
.PP
Provides class that stores information relevant to a given entree.  

.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include 'EntreeTarget.h'\fP
.br

.SH "Detailed Description"
.PP 
Provides class that stores information relevant to a given entree. 

\fBAuthor:\fP
.RS 4
Aaron Alaniz (webheadz3@gmail.com) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
