.TH "jni/Menupp.h" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/Menupp.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBUTTONS\fP { \fBBUTTON_1\fP =  1, \fBBUTTON_2\fP =  2, \fBBUTTON_3\fP =  4, \fBBUTTON_4\fP =  8, \fBBUTTON_5\fP =  16 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBUTTONS\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBUTTON_1 \fP\fP
.TP
\fB\fIBUTTON_2 \fP\fP
.TP
\fB\fIBUTTON_3 \fP\fP
.TP
\fB\fIBUTTON_4 \fP\fP
.TP
\fB\fIBUTTON_5 \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
