.TH "jni/Planes.h" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/Planes.h \- 
.PP
The purpose of this file is to provide the geometric plane definitions that will be utilized in the application for rendering. The rectangular plane is used to bind the descriptions of the entrees and the square plane is used to bind the entree images to.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The purpose of this file is to provide the geometric plane definitions that will be utilized in the application for rendering. The rectangular plane is used to bind the descriptions of the entrees and the square plane is used to bind the entree images to. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
