.TH "srdes::menupp::QCARSampleGLView" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::QCARSampleGLView \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::opengl::GLSurfaceView.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigChooser\fP"
.br
.ti -1c
.RI "class \fBContextFactory\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCARSampleGLView\fP (Context context)"
.br
.ti -1c
.RI "void \fBinit\fP (int flags, boolean translucent, int depth, int stencil)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcheckEglError\fP (String prompt, EGL10 egl)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBmUseOpenGLES2\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQCARSampleGLView\fP is a support class for the QCAR samples applications.
.PP
Responsible for setting up and configuring the OpenGL surface view. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "srdes.menupp.QCARSampleGLView.QCARSampleGLView (Contextcontext)"Constructor. 
.SH "Member Function Documentation"
.PP 
.SS "static void srdes.menupp.QCARSampleGLView.checkEglError (Stringprompt, EGL10egl)\fC [static, private]\fP"Checks the OpenGL error. 
.SS "void srdes.menupp.QCARSampleGLView.init (intflags, booleantranslucent, intdepth, intstencil)"Initialization. 
.SH "Member Data Documentation"
.PP 
.SS "boolean \fBsrdes.menupp.QCARSampleGLView.mUseOpenGLES2\fP = true\fC [static, private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
