.TH "srdes::menupp::QcarEngine::LoadTrackerTask" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::QcarEngine::LoadTrackerTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::os::AsyncTask< Void, Integer, Boolean >.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Boolean \fBdoInBackground\fP (Void...params)"
.br
.ti -1c
.RI "void \fBonProgressUpdate\fP (Integer...values)"
.br
.ti -1c
.RI "void \fBonPostExecute\fP (Boolean result)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An async task to load the tracker data asynchronously. 
.SH "Member Function Documentation"
.PP 
.SS "Boolean srdes.menupp.QcarEngine.LoadTrackerTask.doInBackground (Void...params)\fC [protected]\fP"
.SS "void srdes.menupp.QcarEngine.LoadTrackerTask.onPostExecute (Booleanresult)\fC [protected]\fP"
.SS "void srdes.menupp.QcarEngine.LoadTrackerTask.onProgressUpdate (Integer...values)\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
