.TH "srdes::menupp::MenuList" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::MenuList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::app::ListActivity.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonListItemClick\fP (ListView l, View v, int position, long id)"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String[] \fBmenus\fP"
.br
.ti -1c
.RI "Intent \fBqcarEngine\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void srdes.menupp.MenuList.onCreate (BundlesavedInstanceState)\fC [protected]\fP"
.SS "void srdes.menupp.MenuList.onListItemClick (ListViewl, Viewv, intposition, longid)\fC [protected]\fP"
.SS "void srdes.menupp.MenuList.onPause ()\fC [protected]\fP"
.SS "void srdes.menupp.MenuList.onResume ()\fC [protected]\fP"
.SH "Member Data Documentation"
.PP 
.SS "String [] \fBsrdes.menupp.MenuList.menus\fP\fC [private]\fP"
.SS "Intent \fBsrdes.menupp.MenuList.qcarEngine\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
