.TH "jni/Texture.cpp" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/Texture.cpp \- 
.PP
Implementation of class \fBTexture\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Texture.h'\fP
.br
\fC#include 'Utils.h'\fP
.br
\fC#include <string.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of class \fBTexture\fP. 

\fBNote:\fP
.RS 4
Copyright (c) 2010-2011 QUALCOMM Incorporated. All Rights Reserved. Qualcomm Confidential and Proprietary 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
