.TH "jni/CubeShaders.h" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/CubeShaders.h \- 
.PP
Defines OpenGL shaders as char* strings.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Defines OpenGL shaders as char* strings. 

\fBNote:\fP
.RS 4
Copyright (c) 2010-2011 QUALCOMM Incorporated. All Rights Reserved. Qualcomm Confidential and Proprietary 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
