.TH "EntreeTarget" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntreeTarget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EntreeTarget.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntreeTarget\fP (\fBstring\fP name, int id)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fB~EntreeTarget\fP ()"
.br
.RI "\fIDestructor. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBitemId\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBitemName\fP"
.br
.ti -1c
.RI "bool \fBitemSelected\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EntreeTarget::EntreeTarget (\fBstring\fPname, intid)"
.PP
Constructor. 
.SS "EntreeTarget::~EntreeTarget ()"
.PP
Destructor. 
.SH "Member Data Documentation"
.PP 
.SS "int \fBEntreeTarget.itemId\fP"
.SS "\fBstring\fP \fBEntreeTarget.itemName\fP"
.SS "bool \fBEntreeTarget.itemSelected\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
