.TH "srdes::menupp::AboutUs" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::AboutUs \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::app::Activity.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void srdes.menupp.AboutUs.onCreate (BundlesavedInstanceState)\fC [protected]\fP"
.SS "void srdes.menupp.AboutUs.onDestroy ()\fC [protected]\fP"
.SS "void srdes.menupp.AboutUs.onPause ()\fC [protected]\fP"
.SS "void srdes.menupp.AboutUs.onResume ()\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
