.TH "srdes::menupp::QcarEngine::InitQCARTask" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::QcarEngine::InitQCARTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::os::AsyncTask< Void, Integer, Boolean >.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Boolean \fBdoInBackground\fP (Void...params)"
.br
.ti -1c
.RI "void \fBonPostExecute\fP (Boolean result)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBmProgressValue\fP = -1"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Boolean srdes.menupp.QcarEngine.InitQCARTask.doInBackground (Void...params)\fC [protected]\fP"
.SS "void srdes.menupp.QcarEngine.InitQCARTask.onPostExecute (Booleanresult)\fC [protected]\fP"
.SH "Member Data Documentation"
.PP 
.SS "int \fBsrdes.menupp.QcarEngine.InitQCARTask.mProgressValue\fP = -1\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
