.TH "srdes::menupp::DebugLog" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::DebugLog \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static final void \fBLOGE\fP (String nMessage)"
.br
.ti -1c
.RI "static final void \fBLOGW\fP (String nMessage)"
.br
.ti -1c
.RI "static final void \fBLOGD\fP (String nMessage)"
.br
.ti -1c
.RI "static final void \fBLOGI\fP (String nMessage)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBLOGTAG\fP = 'QCAR'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDebugLog\fP is a support class for the QCAR samples applications.
.PP
Exposes functionality for logging. 
.SH "Member Function Documentation"
.PP 
.SS "static final void srdes.menupp.DebugLog.LOGD (StringnMessage)\fC [static]\fP"
.SS "static final void srdes.menupp.DebugLog.LOGE (StringnMessage)\fC [static]\fP"Logging functions to generate ADB logcat messages. 
.SS "static final void srdes.menupp.DebugLog.LOGI (StringnMessage)\fC [static]\fP"
.SS "static final void srdes.menupp.DebugLog.LOGW (StringnMessage)\fC [static]\fP"
.SH "Member Data Documentation"
.PP 
.SS "final String \fBsrdes.menupp.DebugLog.LOGTAG\fP = 'QCAR'\fC [static, private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
