.TH "srdes::menupp::EntreeEdit" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srdes::menupp::EntreeEdit \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits android::app::Activity.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonSavedInstanceState\fP (Bundle outState)"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBpopulateFields\fP ()"
.br
.ti -1c
.RI "void \fBsaveState\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "EditText \fBmTitleText\fP"
.br
.ti -1c
.RI "EditText \fBmBodyText\fP"
.br
.ti -1c
.RI "Long \fBmRowId\fP"
.br
.ti -1c
.RI "\fBEntreeDbAdapter\fP \fBmDbHelper\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void srdes.menupp.EntreeEdit.onCreate (BundlesavedInstanceState)\fC [protected]\fP"
.SS "void srdes.menupp.EntreeEdit.onPause ()\fC [protected]\fP"
.SS "void srdes.menupp.EntreeEdit.onResume ()\fC [protected]\fP"
.SS "void srdes.menupp.EntreeEdit.onSavedInstanceState (BundleoutState)\fC [protected]\fP"
.SS "void srdes.menupp.EntreeEdit.populateFields ()\fC [private]\fP"
.SS "void srdes.menupp.EntreeEdit.saveState ()\fC [private]\fP"
.SH "Member Data Documentation"
.PP 
.SS "EditText \fBsrdes.menupp.EntreeEdit.mBodyText\fP\fC [private]\fP"
.SS "\fBEntreeDbAdapter\fP \fBsrdes.menupp.EntreeEdit.mDbHelper\fP\fC [private]\fP"
.SS "Long \fBsrdes.menupp.EntreeEdit.mRowId\fP\fC [private]\fP"
.SS "EditText \fBsrdes.menupp.EntreeEdit.mTitleText\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
