.TH "jni/Utils.cpp" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/Utils.cpp \- 
.PP
Implementation of class \fBUtils\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Utils.h'\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <GLES2/gl2.h>\fP
.br
\fC#include <GLES2/gl2ext.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of class \fBUtils\fP. 

\fBNote:\fP
.RS 4
Copyright (c) 2010-2011 QUALCOMM Incorporated. All Rights Reserved. Qualcomm Confidential and Proprietary 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
