.TH "jni/Utils.h" 3 "Tue Feb 28 2012" "Menu++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/Utils.h \- 
.PP
A utility class for application operations.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <android/log.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtils\fP"
.br
.RI "\fIA utility class used by the QCAR SDK samples. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOG_TAG\fP   'IMAGE_TARGETS'"
.br
.ti -1c
.RI "#define \fBLOG\fP(...)   __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A utility class for application operations. 

\fBNote:\fP
.RS 4
Copyright (c) 2010-2011 QUALCOMM Incorporated. All Rights Reserved. Qualcomm Confidential and Proprietary 
.RE
.PP

.SH "Define Documentation"
.PP 
.SS "#define LOG(...)   __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)"
.SS "#define LOG_TAG   'IMAGE_TARGETS'"
.SH "Author"
.PP 
Generated automatically by Doxygen for Menu++ from the source code.
